# Generated by Django 6.0.2 on 2026-02-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requireddocument',
            old_name='name',
            new_name='document_name',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='official_website',
        ),
        migrations.AddField(
            model_name='scheme',
            name='official_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='eligibilityrule',
            name='operator',
            field=models.CharField(choices=[('lt', 'Less Than'), ('gt', 'Greater Than'), ('eq', 'Equal'), ('lte', 'Less Than Equal'), ('gte', 'Greater Than Equal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='states',
            field=models.ManyToManyField(blank=True, to='schemes.state'),
        ),
    ]
