# Generated by Django 6.0.2 on 2026-03-03 13:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0004_eligibilitycheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eligibilitycheck',
            unique_together={('user', 'scheme')},
        ),
    ]
