# Generated by Django 6.0.2 on 2026-03-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0005_alter_eligibilitycheck_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eligibilityrule',
            name='operator',
            field=models.CharField(choices=[('lt', 'Less Than'), ('gt', 'Greater Than'), ('eq', 'Equal'), ('lte', 'Less Than Equal'), ('gte', 'Greater Than Equal'), ('in', 'In List')], max_length=10),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='is_central',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='official_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
