# Generated by Django 6.0.2 on 2026-03-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0007_scheme_description_hi_scheme_description_mr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eligibilitycheck',
            old_name='checked_at',
            new_name='checked_on',
        ),
    ]
