# Generated by Django 6.0.2 on 2026-03-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0008_rename_checked_at_eligibilitycheck_checked_on'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eligibilitycheck',
            unique_together=set(),
        ),
    ]
